export const EndpointTestAccess: string = '/testAccess'
export const EndpointTransactionRegister: string = '/transaction/register'
export const EndpointTransactionRequest: string = '/trnRequest'
export const EndpointTransactionVerify: string = '/transaction/verify'
export const EndpointRefund: string = '/transaction/refund'
